[workspace]
members = [
    "def",
    "gen",
]
resolver = "2"

[package]
name = "ascalon_ar"
version = "0.0.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
memmap2 = "0.8.0"
