[package]
name = "ascalon_ar_def"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde-tuple-vec-map = "1.0.1"

[dev-dependencies]
byteorder = "1.4.3"
object = { version = "0.32.1", features = ["pe"] }
serde_json = "1.0.107"
