[package]
name = "ascalon_ar_gen"
version = "0.0.0"
edition = "2021"

[dependencies]
ascalon_ar_def = { path = "../def" }
serde_json = "1.0.107"

convert_case = "0.6.0"
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = "2.0.37"
